### ISSUE TITLE
g2o

### ISSUE THREAD

**Issue by dfridovi** [erik-nelson/berkeley_sfm#4]
Next big step: Implement multi-frame, multi-point bundle adjustment in the g2o framework.

**Comment by erik-nelson** [comment]
Yup. I forgot we had decided on g2o and began coding up BA using ceres. We should think a little about what problem we actually want to optimize with g2o, since we can solve vanilla BA pretty easily with ceres too.

**Comment by dfridovi** [comment]
Ok yeah makes sense. Maybe we can take a first crack at it with ceres and if we later switch to g2o it may not be too bad
